# fly.toml app configuration file generated for nekochat-empty-night-9043 on 2023-11-29T18:05:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nekochat-empty-night-9043"
primary_region = "gru"

[build]

[env]
  PORT = "4200"

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 4200

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
